name: Dotfile Docker Build Test 

on:
  push:
    branches:
      - trunk 

  env:
    # TODO: Change variable to your image's name.
    IMAGE_NAME: srepollock/dotfiles 

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME