name: Dotfile Docker Build Test 

on:
  push:
    branches:
      - trunk 

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag srepollock/dotfiles